# torchtitan Config.toml

[job]
dump_folder = "./outputs"
description = "Llama2 7B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
validation_freq = 100
rank_0_only = true

enable_color_printing = true
enable_tensorboard = true
save_tb_folder = "tb"

[datasets]
catalytic_seq_names = ""
catalytic_sites_names = ""
solubility_train_seq_names = "netsolp/PSI_Biology/pET_full_without_his_tag_consolidated.fasta"
solubility_train_sasa_data = "netsolp/PSI_Biology/pET_full_without_his_tag_sasa_data_consolidated.npz"
solubility_val_seq_names = "netsolp/PSI_Biology/NESG_testset_sasa_data_consolidated.fasta"
solubility_val_sasa_data = "netsolp/PSI_Biology/NESG_testset_sasa_data_consolidated.npz"

[model]
name = "llama2"
flavor = "7B"
norm_type = "fused_rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "./torchtitan/datasets/tokenizer/tokenizer.model"
# final_output = "catalytic-sites"  # can be amino-acids or catalytic-sites or both
final_output = "sasa"

[optimizer]
name = "AdamW"
lr = 3e-4

[training]
batch_size = 24
val_batch_size = 192
seq_len = 256
warmup_steps = 200  # lr scheduler warm up, normally 20% of the train steps
max_norm = 1.0  # grad norm clipping
steps = 50000
data_parallel_degree = -1
tensor_parallel_degree = 1  # dp-only would be sufficient for 7B
pipeline_parallel_degree = 1
fp8_linear = ""
compile = false
dataset = "c4"
enable_loss_parallel = false
gc_freq = 50

[experimental]
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 50
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]
keep_latest_k = 0

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[comm]
trace_buf_size = 20000
init_timeout_seconds = 300